driver:
  name: dokken
  privileged: true # because Docker and SystemD/Upstart
  chef_version: current
  userns_host: true # neede so docker service will run

transport:
  name: dokken

provisioner:
  name: dokken
  deprecations_as_errors: true
  chef_license: accept
  
platforms:
  - name: debian-10
    driver:
      image: dokken/debian-10
      pid_one_command: /bin/systemd
